<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Nexus.Core\Nexus.Core.csproj" />
    <ProjectReference Include="..\Nexus.Contracts\Nexus.Contracts.csproj" />
    <ProjectReference Include="..\Nexus.Simulation\Nexus.Simulation.csproj" />
    <ProjectReference Include="..\Nexus.Diagnostics\Nexus.Diagnostics.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

</Project>
